package main

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
)

// ============================================================================
// Aggregate Claude Code integration.
//
// Each feature writes its own pointer doc at <root>/<feature>/CLAUDE.md. Rather
// than inject one `@import` per feature into the user's global ~/.claude/
// CLAUDE.md (which grows a new block every time a feature ships), zvk builds a
// single aggregate <root>/CLAUDE.md that @import's whichever feature docs exist,
// and injects exactly ONE line into the global file.
//
// refreshZvkClaudeMd is called after any feature writes its doc (zig install,
// self-install). It also migrates older layouts: the injector strips any prior
// per-feature zvk imports so an upgrade collapses them into the single line.
//
// Gated by ZVK_NO_DOCS (skip everything) / ZVK_NO_CLAUDE_MD (build the
// aggregate but don't touch the global file).
// ============================================================================

// featureClaudeDocs lists per-feature doc directories under <root>, in the
// order they appear in the aggregate.
var featureClaudeDocs = []struct{ dir, title string }{
	{"zig", "Zig toolchain (version selection + per-build reference)"},
	{"fetch", "Browser-fingerprint HTTP fetch (anti-bot pages)"},
	{"serve", "HTTP share (serve a generated report)"},
}

func refreshZvkClaudeMd(root string, stdout io.Writer) {
	if os.Getenv("ZVK_NO_DOCS") != "" {
		return
	}
	absRoot, err := filepath.Abs(root)
	if err != nil {
		absRoot = root
	}

	var b strings.Builder
	b.WriteString("# zvk — Claude Code integration\n\n")
	b.WriteString("Auto-generated by zvk. Do not edit — overwritten by zvk commands.\n")
	b.WriteString("Disable with `ZVK_NO_CLAUDE_MD=1`.\n\n")
	b.WriteString("zvk-managed tools in this environment (each `@` line imports its doc):\n\n")
	any := false
	for _, f := range featureClaudeDocs {
		p := filepath.Join(absRoot, f.dir, "CLAUDE.md")
		if fileExists(p) {
			fmt.Fprintf(&b, "## %s\n@%s\n\n", f.title, p)
			any = true
		}
	}
	if !any {
		return
	}

	aggPath := filepath.Join(absRoot, "CLAUDE.md")
	if err := writeFileAtomic(aggPath, []byte(b.String()), 0o644); err != nil {
		fmt.Fprintf(stdout, "[zvk] note: could not write %s: %v\n", aggPath, err)
		return
	}
	if os.Getenv("ZVK_NO_CLAUDE_MD") != "" {
		return
	}
	if err := injectAggregateImport(absRoot, aggPath); err != nil {
		fmt.Fprintf(stdout, "[zvk] note: could not link CLAUDE.md into ~/.claude/CLAUDE.md: %v\n", err)
	}
}

// injectAggregateImport makes ~/.claude/CLAUDE.md @import the aggregate exactly
// once, removing any prior zvk-injected lines first: the aggregate import
// itself (idempotent re-run) and legacy per-feature imports under <root>, along
// with the "# Added by zvk" markers that preceded them.
func injectAggregateImport(root, aggPath string) error {
	home, err := os.UserHomeDir()
	if err != nil {
		return err
	}
	globalPath := filepath.Join(home, ".claude", "CLAUDE.md")
	existing, err := os.ReadFile(globalPath)
	if err != nil && !os.IsNotExist(err) {
		return err
	}

	importLine := "@" + aggPath
	rootPrefix := "@" + root + string(filepath.Separator)

	var kept []string
	for _, ln := range strings.Split(string(existing), "\n") {
		t := strings.TrimSpace(ln)
		switch {
		case t == "# Added by zvk":
			continue
		case t == importLine:
			continue
		case strings.HasPrefix(t, rootPrefix) && strings.HasSuffix(t, "CLAUDE.md"):
			// Legacy per-feature import (@<root>/<feature>/CLAUDE.md).
			continue
		}
		kept = append(kept, ln)
	}
	for len(kept) > 0 && strings.TrimSpace(kept[len(kept)-1]) == "" {
		kept = kept[:len(kept)-1]
	}

	buf := strings.Join(kept, "\n")
	if len(buf) > 0 {
		buf += "\n"
	}
	buf += "\n# Added by zvk\n" + importLine + "\n"

	if err := os.MkdirAll(filepath.Dir(globalPath), 0o755); err != nil {
		return err
	}
	return os.WriteFile(globalPath, []byte(buf), 0o644)
}
