package main

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
)

// ============================================================================
// Claude Code awareness for `zvk fetch`.
//
// `zvk fetch` only helps if the assistant knows to reach for it. Mirroring
// zigdoc.go, self-install lays down <root>/fetch/CLAUDE.md and idempotently
// @import's it into ~/.claude/CLAUDE.md, so every session learns that a
// browser-fingerprinting fetcher exists and when to prefer it over the built-in
// WebFetch (which presents a Go TLS fingerprint and gets challenged/403'd by
// anti-bot edges).
//
// Gated by ZVK_NO_DOCS (skip entirely) / ZVK_NO_CLAUDE_MD (write the doc but
// don't inject the global import). Best-effort: a failure prints an advisory
// and never fails self-install.
// ============================================================================

func writeFetchDoc(root string, stdout io.Writer) {
	if os.Getenv("ZVK_NO_DOCS") != "" {
		return
	}
	absRoot, err := filepath.Abs(root)
	if err != nil {
		absRoot = root
	}
	claudePath := filepath.Join(absRoot, "fetch", "CLAUDE.md")
	if err := writeFileAtomic(claudePath, []byte(fetchClaudeMd()), 0o644); err != nil {
		fmt.Fprintf(stdout, "[zvk fetch] note: could not write CLAUDE.md: %v\n", err)
		return
	}
	if os.Getenv("ZVK_NO_CLAUDE_MD") == "" {
		if err := injectGlobalImport(claudePath); err != nil {
			fmt.Fprintf(stdout, "[zvk fetch] note: could not link CLAUDE.md into ~/.claude/CLAUDE.md: %v\n", err)
			return
		}
	}
	fmt.Fprintf(stdout, "[zvk fetch] Claude Code awareness written to %s\n", claudePath)
}

// fetchClaudeMd is the pointer loaded into the assistant's context: what the
// tool is, when to choose it over WebFetch, and copy-pasteable invocations.
func fetchClaudeMd() string {
	return "# Browser-fingerprint fetch (managed by zvk)\n\n" +
		"Auto-generated by zvk. Do not edit — overwritten on next `zvk self-install`.\n" +
		"Disable with `ZVK_NO_CLAUDE_MD=1`.\n\n" +
		"## What\n\n" +
		"`zvk fetch <url>` issues an HTTP request that impersonates the latest\n" +
		"Chrome's **TLS + HTTP/2 fingerprint** (ClientHello / JA3, HTTP/2 SETTINGS,\n" +
		"header order, pseudo-header order), not just its User-Agent string.\n\n" +
		"## When to use it instead of WebFetch / curl\n\n" +
		"WebFetch, curl and Go's net/http present a non-browser TLS fingerprint that\n" +
		"anti-bot edges (Cloudflare, Akamai, PerimeterX, DataDome) detect and answer\n" +
		"with a challenge page, 403, or 503. **When a page returns a challenge/block,\n" +
		"empty content, or an \"enable JavaScript\" wall, retry with `zvk fetch`** — it\n" +
		"presents a real Chrome fingerprint and usually gets the genuine content.\n\n" +
		"It does NOT execute JavaScript — it's an HTTP client, not a headless\n" +
		"browser. For SPA content that only renders client-side, it returns the raw\n" +
		"HTML shell.\n\n" +
		"## Usage\n\n" +
		"```sh\n" +
		"zvk fetch https://example.com                 # body to stdout, latest Chrome\n" +
		"zvk fetch -i https://example.com              # include response headers\n" +
		"zvk fetch -o page.html https://example.com    # write body to a file\n" +
		"zvk fetch -X POST -H 'Content-Type: application/json' \\\n" +
		"  -d '{\"q\":1}' https://api.example.com/v1     # JSON POST\n" +
		"zvk fetch --profile firefox_133 <url>         # a specific profile\n" +
		"zvk fetch --list-profiles                     # all impersonation profiles\n" +
		"```\n\n" +
		"Default is the latest Chrome; `--profile <name>` selects any other browser\n" +
		"fingerprint. A status line is printed to stderr (suppress with `-s`), so\n" +
		"stdout stays clean for piping the body.\n"
}
